apiVersion: v1 # versao da API do Kubernetes
kind: Service # tipo de objeto criado, nesse caso, um Service
metadata: # metadados do objeto
  name: nginx # nome do Service
  labels: # definicao de labels do Service
    app: nginx # label app com valor nginx
    env: dev # label env com valor dev
spec: # especificacao do servico
  selector: # definicao do selector referente ao pods para esse Service
    app: nginx # pods com label app serao expostos por esse Service
  ports: # definicao das portas do Service
  - port: 80 # service na porta 80
    protocol: TCP # protocolo de comunicacao TCP(Transmission Control Protocol)
    name: http # descricao para a porta
    targetPort: 80 # porta do container
  - port: 27017
    protocol: TCP
    name: database
    targetPort: 27017  
  type: ClusterIP # tipo de servico interno, ou seja, acessível somente de dentro do cluster
