apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
  name: nginx-giropops
spec:
  containers:
  - image: nginx
    name: nginx-giropops
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
